using ReactiveUI;
using ReactiveUI.Fody.Helpers;

namespace DebuggingTool.Model;

/// <summary>
/// A demonstration of a Form ViewModel.
/// The `property:` part is to target the property generated by CommunityToolkits sourcegen.
/// </summary>
public partial class FormViewModel : ReactiveObject
{
    [Reactive]
    public string IP { get; set; } = "127.0.0.1";
    [Reactive]
    public int Port { get; set; } = 102;
}

public partial class ChildFormViewModel : ReactiveObject
{

}
